# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitmate < Formula
  desc "AI-powered Git commit message generator"
  homepage "https://github.com/leehosu/commitmate"
  version "1.0.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leehosu/commitmate/releases/download/v1.0.0/commitmate_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "af7a5746790bf583411645f000807606332ae65eac760272ccaa7c7451f51599"

      def install
        bin.install "commitmate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leehosu/commitmate/releases/download/v1.0.0/commitmate_1.0.0_Darwin_arm64.tar.gz"
      sha256 "4ea7a4f6085a7b6c6a37b0ac954c062b8c0bdfcfa83dca375ad3085ba151cf30"

      def install
        bin.install "commitmate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leehosu/commitmate/releases/download/v1.0.0/commitmate_1.0.0_Linux_x86_64.tar.gz"
      sha256 "3a3f016713a6d629521e8ef9eb7eaa823485e0e52c1446346dd8dadf895e3524"
      def install
        bin.install "commitmate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leehosu/commitmate/releases/download/v1.0.0/commitmate_1.0.0_Linux_arm64.tar.gz"
      sha256 "3af57c2bb7d521b14d2b625e2f0ec6f6adc1359d8df448497c0ac2c0f30c01cb"
      def install
        bin.install "commitmate"
      end
    end
  end

  test do
    system "#{bin}/commitmate", "version"
  end
end
