# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitmate < Formula
  desc "AI-powered Git commit message generator"
  homepage "https://github.com/leehosu/commitmate"
  version "1.0.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leehosu/commitmate/releases/download/v1.0.0/commitmate_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "fadac9f5085d75ac1eb8de42ba84d528f91bdafcf33230c428ff37f5a92f386b"

      def install
        bin.install "commitgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leehosu/commitmate/releases/download/v1.0.0/commitmate_1.0.0_Darwin_arm64.tar.gz"
      sha256 "2cf3d428bcca8ad4b57011686dac94647ad5b19ea8b0c24a573539d8e774624c"

      def install
        bin.install "commitgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leehosu/commitmate/releases/download/v1.0.0/commitmate_1.0.0_Linux_x86_64.tar.gz"
      sha256 "02213da26e57e11d598cb9dc7653fd97f4d92c4943a2e76d444dba9232525a55"
      def install
        bin.install "commitgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leehosu/commitmate/releases/download/v1.0.0/commitmate_1.0.0_Linux_arm64.tar.gz"
      sha256 "669d6517bab798e44d4e531871d697942957362cd11797006de431611d324e4c"
      def install
        bin.install "commitgen"
      end
    end
  end

  test do
    system "#{bin}/commitgen", "version"
  end
end
