# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitgen < Formula
  desc "AI-powered Git commit message generator"
  homepage "https://github.com/leehosu/commitgen"
  version "0.2.1"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leehosu/commitgen/releases/download/v0.2.1/commitgen_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "85ddf2e42aa3803b6f655e12a95937a5c507e6fd1e01a33162811103f2ae3702"

      def install
        bin.install "commitgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leehosu/commitgen/releases/download/v0.2.1/commitgen_0.2.1_Darwin_arm64.tar.gz"
      sha256 "91e9a3a3fb2e0c8a12ccbda8fc5fe7e2eb73699b666f9e3ebbacd959bfeba908"

      def install
        bin.install "commitgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leehosu/commitgen/releases/download/v0.2.1/commitgen_0.2.1_Linux_x86_64.tar.gz"
      sha256 "ea78a8163e0def4333dda5e85ea68bbddbe8979eddaadc304717e6c361ce5a72"
      def install
        bin.install "commitgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leehosu/commitgen/releases/download/v0.2.1/commitgen_0.2.1_Linux_arm64.tar.gz"
      sha256 "8860254d2b304230191b82c459de6e65c083ef1d6647108841f91c5b67d69d31"
      def install
        bin.install "commitgen"
      end
    end
  end

  test do
    system "#{bin}/commitgen", "version"
  end
end
